# Generated by Django 2.2.7 on 2020-02-11 10:31

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('com', '0006_schoolclass'),
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('userName', models.CharField(max_length=50)),
                ('birthdate', models.DateField(default=datetime.date(1997, 11, 11), max_length=90, null=True)),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None)),
                ('email', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('loginID', models.CharField(max_length=255, unique=True)),
                ('is_staff', models.BooleanField(default=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.IntegerField()),
                ('gender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='com.code')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('RoleID', models.AutoField(primary_key=True, serialize=False)),
                ('RoleName', models.CharField(max_length=50, unique=True)),
                ('RoleDescription', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='UserRole',
            fields=[
                ('userRoleID', models.AutoField(primary_key=True, serialize=False)),
                ('RoleID', models.ForeignKey(db_column='RoleID', on_delete=django.db.models.deletion.CASCADE, to='myapp.Role')),
                ('userID', models.ForeignKey(db_column='userID', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserRoleLocation',
            fields=[
                ('userRoleLocationID', models.AutoField(db_column='userRoleLocation', primary_key=True, serialize=False)),
                ('locationObjectID', models.ForeignKey(db_column='locationObjectID', on_delete=django.db.models.deletion.CASCADE, to='com.school')),
                ('locationTypeCodeID', models.ForeignKey(db_column='locationTypeCodeID', on_delete=django.db.models.deletion.CASCADE, to='com.code')),
                ('userRoleID', models.ForeignKey(db_column='userRoleID', on_delete=django.db.models.deletion.CASCADE, to='myapp.UserRole')),
            ],
        ),
    ]
