# Generated by Django 2.2.7 on 2020-02-12 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userrolelocation',
            name='locationObjectID',
            field=models.IntegerField(),
        ),
    ]
