# Generated by Django 2.2.7 on 2020-01-24 13:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('com', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('addressID', models.AutoField(db_column='AddressID', primary_key=True, serialize=False)),
                ('line1', models.TextField(db_column='Line1')),
                ('line2', models.TextField(db_column='Line2')),
                ('city', models.CharField(max_length=20)),
                ('districtID', models.ForeignKey(db_column='districtID', on_delete=django.db.models.deletion.CASCADE, to='com.Districts')),
                ('stateID', models.ForeignKey(db_column='stateID', on_delete=django.db.models.deletion.CASCADE, to='com.States')),
                ('pincode', models.IntegerField()),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=10)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=10)),
                ('countryID', models.ForeignKey(db_column='countryID', on_delete=django.db.models.deletion.CASCADE, to='com.Countries')),
              
            ],
        ),
    ]
