# Generated by Django 2.2.7 on 2020-01-24 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('com', '0002_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='codeGroup',
            fields=[
                ('codeGroupID', models.AutoField(db_column='codeGroupID', primary_key=True, serialize=False)),
                ('codeGroupName', models.CharField(db_column='codeGroupName', max_length=100)),
            ],
        ),
    ]
