# Generated by Django 2.2.7 on 2020-01-24 15:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('com', '0003_codegroup'),
    ]

    operations = [
        migrations.CreateModel(
            name='code',
            fields=[
                ('codeID', models.AutoField(db_column='codeID', primary_key=True, serialize=False)),
                ('codeGroupID', models.ForeignKey(db_column='codeGroupID', on_delete=django.db.models.deletion.CASCADE, to='com.codeGroup')),
                ('codeName', models.CharField(db_column='codeName', max_length=100)),
            ],
        ),
    ]
