# Generated by Django 2.2.7 on 2020-01-24 15:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('com', '0004_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='school',
            fields=[
                ('schoolID', models.AutoField(db_column='schoolID', primary_key=True, serialize=False)),
                ('schoolName', models.CharField(db_column='schoolName', max_length=100)),
                ('schoolTypeCodeID', models.ForeignKey(db_column='schoolTypeCodeID', on_delete=django.db.models.deletion.CASCADE, to='com.code')),
                ('addressID', models.ForeignKey(db_column='addressID', on_delete=django.db.models.deletion.CASCADE, to='com.Address')),
                ('UDISEcode', models.IntegerField()),
                ('tag', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=10)),
                   ],
        ),
    ]
