# Generated by Django 2.2.7 on 2020-01-24 16:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('com', '0005_school'),
    ]

    operations = [
        migrations.CreateModel(
            name='schoolClass',
            fields=[
                ('schoolClassID', models.AutoField(db_column='schoolClassID', primary_key=True, serialize=False)),               
                ('schoolID', models.ForeignKey(db_column='schoolID', on_delete=django.db.models.deletion.CASCADE, to='com.school')),
                ('classNumber', models.IntegerField(db_column='classNumber')),
            ],
        ),
    ]
