# Generated by Django 2.2.7 on 2020-02-11 16:44

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('com', '0006_schoolclass'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None),
        ),
    ]
