# Generated by Django 2.2.7 on 2020-02-13 06:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('com', '0008_auto_20200212_2249'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ques', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='competition',
            fields=[
                ('competitionID', models.AutoField(db_column='competitionID', primary_key=True, serialize=False)),
                ('competitionName', models.CharField(max_length=50)),
                ('competitionInfo', models.CharField(max_length=100)),
                ('startDate', models.DateTimeField()),
                ('endDate', models.DateTimeField()),
                ('testDuration', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='competitionAge',
            fields=[
                ('competitionAgeID', models.AutoField(db_column='competitionAgeID', primary_key=True, serialize=False)),
                ('competitionID', models.ForeignKey(db_column='competitionID', on_delete=django.db.models.deletion.CASCADE, to='cmp.competition')),
                ('schoolClassID', models.ForeignKey(db_column='schoolClassID', on_delete=django.db.models.deletion.CASCADE, to='com.schoolClass')),
            ],
        ),
        migrations.CreateModel(
            name='competitionQuestion',
            fields=[
                ('competitionQuestionID', models.AutoField(db_column='competitionQuestionID', primary_key=True, serialize=False)),
                ('competitionAgeID', models.ForeignKey(db_column='competitionAgeID', on_delete=django.db.models.deletion.CASCADE, to='cmp.competitionAge')),
                ('questionID', models.ForeignKey(db_column='questionID', on_delete=django.db.models.deletion.CASCADE, to='ques.question')),
                ('questionLevelCodeID', models.ForeignKey(db_column='codeID', on_delete=django.db.models.deletion.CASCADE, to='com.code')),
            ],
        ),
        migrations.CreateModel(
            name='studentEnrollment',
            fields=[
                ('studentEnrollmentID', models.AutoField(db_column='studentEnrollmentID', primary_key=True, serialize=False)),
                ('timeTaken', models.TimeField()),
                ('score', models.IntegerField()),
                ('competitionAgeID', models.ForeignKey(db_column='competitionAgeID', on_delete=django.db.models.deletion.CASCADE, to='cmp.competitionAge')),
                ('languageCodeID', models.ForeignKey(db_column='codeID', on_delete=django.db.models.deletion.CASCADE, to='com.code')),
                ('userID', models.ForeignKey(db_column='userID', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='studentResponse',
            fields=[
                ('studentResponseID', models.AutoField(db_column='studentResponseID', primary_key=True, serialize=False)),
                ('competitionQuestionID', models.ForeignKey(db_column='competitionQuestionID', on_delete=django.db.models.deletion.CASCADE, to='cmp.competitionQuestion')),
                ('optionID', models.ForeignKey(db_column='option', on_delete=django.db.models.deletion.CASCADE, to='ques.option')),
                ('studentEnrollmentID', models.ForeignKey(db_column='studentEnrollmentID', on_delete=django.db.models.deletion.CASCADE, to='cmp.studentEnrollment')),
            ],
        ),
        migrations.CreateModel(
            name='competition_MarkScheme',
            fields=[
                ('competition_MarkSchemeID', models.AutoField(db_column='competition_MarkSchemeID', primary_key=True, serialize=False)),
                ('correctMarks', models.IntegerField()),
                ('incorrectMarks', models.IntegerField()),
                ('competitionAgeID', models.ForeignKey(db_column='competitionAgeID', on_delete=django.db.models.deletion.CASCADE, to='cmp.competitionAge')),
                ('questionLevelCodeID', models.ForeignKey(db_column='codeID', on_delete=django.db.models.deletion.CASCADE, to='com.code')),
            ],
        ),
    ]
