# Generated by Django 2.2.7 on 2020-02-20 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmp', '0002_auto_20200220_2314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentenrollment',
            name='score',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='studentenrollment',
            name='timeTaken',
            field=models.TimeField(null=True),
        ),
    ]
